name: CI

on:
  push:
    tags: [ v*.*.* ]
  pull_request:
    tags: [ v*.*.* ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/package-lock.json') }}

      - name: Build
        run: |
          npm install
          npm run build:prod

      - name: Publish
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
