name: Build

on:
  push:
    branches:
      - release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Build
        run: |
          npm install
          npm run build:prod
      - name: Upload release
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: release
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download release
        uses: actions/download-artifact@v2
        with:
          name: release
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          login-server: ${{ secrets.DOCKER_REGISTRY }}
          password: ${{ secrets.DOCKER_PWD }}
      - name: Publish
        run: |
          IMAGE=registry.cn-shenzhen.aliyuncs.com/zdhd-project/pigeon-admin
          docker build --tag $IMAGE:latest .
          docker push $IMAGE:latest
